### ISSUE TITLE
Installing on Mac

### ISSUE THREAD

**Issue by idkjs** [kritzcreek/vessel#12]
I have tried to follow the directions provided.

After downloading macos binary from releases, I am unable to open it. I get an error:

![Screen Shot 2020-09-06 at 1 16 40 PM](https://user-images.githubusercontent.com/2370391/92331232-3cb21400-f043-11ea-9914-17bf15199746.png)

How do I install vessel after downloading it? 

Thank you.

**Comment by kritzcreek** [comment]
It's a binary. You should move it to a location that's on your path and rename it to `vessel`. You probably also need to run `chmod +x vessel` on it.

**Comment by idkjs** [comment]
here is what I have done.

```sh
❯ ls $HOME
Applications/ Exercism/     Movies/       Public/       gist/         smlformat/
Desktop/      Github/       Music/        bin/          node_modules/ vessel*
Documents/    Heroku/       Pictures/     docs/         npmbin@
Downloads/    Library/      Postman/      dotfiles/     polyml/
```

Im in fish shell:

```sh
~/.config/fish master* ⇡
❯ set -Ua fish_user_paths $HOME/vessel
```

Running `vessel init` gets me ```sh
❯ vessel init
fish: Unknown command: vessel
```

Though it works if I run vessel init from the same directory that its in. So likely i am setting the path wrong....

**Comment by idkjs** [comment]
Thanks.

```sh
❯ wget -O $HOME/bin/vessel https://github.com/kritzcreek/vessel/releases/download/v0.4.1/vessel-macos
~/Downloads/MOKOTO/calculator2 master
❯ set -Ua fish_user_paths $HOME/bin/

~/Downloads/MOKOTO/calculator2 master
❯ fish
~/Downloads/MOKOTO/calculator2 master
❯ which vessel
/Users/mandalarian/bin//vessel
```
