### ISSUE TITLE
Hash mismatch?

### ISSUE THREAD

**Issue by ninegua** [kritzcreek/vessel#16]
When doing `nix-build` I ran into the following error (on Linux, but I think platform shouldn't matter):

```
installing
hash mismatch in fixed-output derivation '/nix/store/l6h129fiylvpky3izl1whhqwgw4qd710-vessel-1.0.0-vendor.tar.gz':
  wanted: sha256:0kykwbqhh4zm4si0ibr89m3vas7ldpg90r8kjfv0qn5mr22zw48c
  got:    sha256:07rz0gm6yqxmi34dzgia31h1kvk70xa3rb7h7ygl6pylx71grwbj
cannot build derivation '/nix/store/7rn7qpl5fwbyjgi3lndqs3ji79xjhq5f-vessel-1.0.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/1f9brm017w2k82hnsdg5ss37rzs4aqjm-all-systems-go.drv', '/nix/store/7rn7qpl5fwbyjgi3lndqs3ji79xjhq5f-vessel-1.0.0.drv', '/nix/store/kwb601s7bdvysfrlfanf1p83inwhqqf2-vessel-1.0.0.drv' failed
```

So I had to fix the sha256 in default.nix to proceed.

Also, when compiling rust packages I see a lot of packages being compiled twice. Is this expected?

**Comment by kritzcreek** [comment]
> So I had to fix the sha256 in default.nix to proceed.

Right, that hash should've been updated when I updated the dependency versions. I don't use nix myself when working on vessel, but we should probably run `nix-build` in CI at least. I'm not excited about that as it'll double the CI times and I don't have any regular nix contributors.

> Also, when compiling rust packages I see a lot of packages being compiled twice. Is this expected?

I also saw this, but as a non-regular nix user I have no clue why. I assumed it was building both the executable and then test targets, but I'm not quite sure.
