### ISSUE TITLE
Pass-through logic for additional package name-path pairs

### ISSUE THREAD

**Issue by matthewhammer** [kritzcreek/vessel#6]
Current usage within `dfx` as a `packtool`:

  `vessel sources`

New usage:

  `vessel sources [--package name path]*`

Where the additional `--package` name/path pairs are added to those provided by `vessel sources` (logic to resolve duplicates, etc, is optional).

See also: https://github.com/dfinity/motoko-bigmap/pull/16

**Comment by kritzcreek** [comment]
We figured out a workaround and I'd like to keep `vessel` simple until we can't anymore.
